### ISSUE TITLE
'0000-00-00'在MySQL Version: 5.7.9中认为是错误的日期范围.

### ISSUE THREAD

**Issue by momoca** [liu21st/onethink#23]
.\oneThink\Application\Install\Data\install.sql中的
`birthday` date NOT NULL DEFAULT '0000-00-00' COMMENT '生日',
应该改为
`birthday` DATE NULL DEFAULT '1000-01-01' COMMENT '生日',

因为'0000-00-00'在MySQL Version: 5.7.9中认为是错误的日期范围.

**Comment by momoca** [comment]
还有.\oneThink\Application\Install\Common\function.php中的
$sql = "INSERT INTO `[PREFIX]member` VALUES ".
           "('1', '[NAME]', '0', '0000-00-00', '', '0', '1', '0', '[TIME]', '0', '[TIME]', '1');";
应该改为
$sql = "INSERT INTO `[PREFIX]member` VALUES ".
           "('1', '[NAME]', '0', '1000-01-01', '', '0', '1', '0', '[TIME]', '0', '[TIME]', '1');";

**Comment by LD8** [comment]
这个地方没有问题，5.7.9-log的版本，你最好自己用SQL再测试一下。

**Comment by Tonkong** [comment]
mysql 5.7.9 不能设置'0000-00-00'，要修改配置文件my.cnf, 查找删除STRICT_TRANS_TABLES（严格模式）
